=== D4bleGunInVador/Programming_for_the_Internet/M1-2/PART3/passport.dtd
<!ELEMENT passport (header, photo, details, footer)>
<!ELEMENT header (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT details (first_name, last_name, middle_name, address, id_number)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT middle_name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT id_number (#PCDATA)>
<!ELEMENT footer (#PCDATA)>

=== D4bleGunInVador/Programming_for_the_Internet/PART3/passport.xml
<?xml version="1.0" encoding="windows-1251"?>
<!DOCTYPE passport SYSTEM "passport.dtd">
<?xml-stylesheet type="text/css" href="passport.css"?>
<passport>
    <header>Національний Паспорт</header>
    <photo>photo.jpg</photo>
    <details>
        <first_name>Хосе</first_name>
        <last_name>Петров</last_name>
        <middle_name>Іванович</middle_name>
        <address>Київ, вул. Шевченка, 12</address>
        <id_number>ІПН:123456789</id_number>
    </details>
    <footer>001333012293</footer>
</passport>
